// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common-mb/dal/model"
)

func newAgentEmergencySnapshot(db *gorm.DB, opts ...gen.DOOption) agentEmergencySnapshot {
	_agentEmergencySnapshot := agentEmergencySnapshot{}

	_agentEmergencySnapshot.agentEmergencySnapshotDo.UseDB(db, opts...)
	_agentEmergencySnapshot.agentEmergencySnapshotDo.UseModel(&model.AgentEmergencySnapshot{})

	tableName := _agentEmergencySnapshot.agentEmergencySnapshotDo.TableName()
	_agentEmergencySnapshot.ALL = field.NewAsterisk(tableName)
	_agentEmergencySnapshot.ID = field.NewInt64(tableName, "id")
	_agentEmergencySnapshot.MinionID = field.NewInt64(tableName, "minion_id")
	_agentEmergencySnapshot.Inet = field.NewString(tableName, "inet")
	_agentEmergencySnapshot.Type = field.NewString(tableName, "type")
	_agentEmergencySnapshot.Value = field.NewBytes(tableName, "value")
	_agentEmergencySnapshot.CreatedAt = field.NewTime(tableName, "created_at")
	_agentEmergencySnapshot.ReportedAt = field.NewTime(tableName, "reported_at")
	_agentEmergencySnapshot.UpdatedAt = field.NewTime(tableName, "updated_at")

	_agentEmergencySnapshot.fillFieldMap()

	return _agentEmergencySnapshot
}

type agentEmergencySnapshot struct {
	agentEmergencySnapshotDo agentEmergencySnapshotDo

	ALL        field.Asterisk
	ID         field.Int64 // ID
	MinionID   field.Int64 // 节点ID
	Inet       field.String
	Type       field.String // 快照类型
	Value      field.Bytes  // 快照数据
	CreatedAt  field.Time   // 创建时间
	ReportedAt field.Time   // 上报时间
	UpdatedAt  field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a agentEmergencySnapshot) Table(newTableName string) *agentEmergencySnapshot {
	a.agentEmergencySnapshotDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentEmergencySnapshot) As(alias string) *agentEmergencySnapshot {
	a.agentEmergencySnapshotDo.DO = *(a.agentEmergencySnapshotDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentEmergencySnapshot) updateTableName(table string) *agentEmergencySnapshot {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.MinionID = field.NewInt64(table, "minion_id")
	a.Inet = field.NewString(table, "inet")
	a.Type = field.NewString(table, "type")
	a.Value = field.NewBytes(table, "value")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.ReportedAt = field.NewTime(table, "reported_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *agentEmergencySnapshot) WithContext(ctx context.Context) *agentEmergencySnapshotDo {
	return a.agentEmergencySnapshotDo.WithContext(ctx)
}

func (a agentEmergencySnapshot) TableName() string { return a.agentEmergencySnapshotDo.TableName() }

func (a agentEmergencySnapshot) Alias() string { return a.agentEmergencySnapshotDo.Alias() }

func (a agentEmergencySnapshot) Columns(cols ...field.Expr) gen.Columns {
	return a.agentEmergencySnapshotDo.Columns(cols...)
}

func (a *agentEmergencySnapshot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentEmergencySnapshot) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["minion_id"] = a.MinionID
	a.fieldMap["inet"] = a.Inet
	a.fieldMap["type"] = a.Type
	a.fieldMap["value"] = a.Value
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["reported_at"] = a.ReportedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a agentEmergencySnapshot) clone(db *gorm.DB) agentEmergencySnapshot {
	a.agentEmergencySnapshotDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentEmergencySnapshot) replaceDB(db *gorm.DB) agentEmergencySnapshot {
	a.agentEmergencySnapshotDo.ReplaceDB(db)
	return a
}

type agentEmergencySnapshotDo struct{ gen.DO }

func (a agentEmergencySnapshotDo) Debug() *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Debug())
}

func (a agentEmergencySnapshotDo) WithContext(ctx context.Context) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentEmergencySnapshotDo) ReadDB() *agentEmergencySnapshotDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentEmergencySnapshotDo) WriteDB() *agentEmergencySnapshotDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentEmergencySnapshotDo) Session(config *gorm.Session) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentEmergencySnapshotDo) Clauses(conds ...clause.Expression) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentEmergencySnapshotDo) Returning(value interface{}, columns ...string) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentEmergencySnapshotDo) Not(conds ...gen.Condition) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentEmergencySnapshotDo) Or(conds ...gen.Condition) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentEmergencySnapshotDo) Select(conds ...field.Expr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentEmergencySnapshotDo) Where(conds ...gen.Condition) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentEmergencySnapshotDo) Order(conds ...field.Expr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentEmergencySnapshotDo) Distinct(cols ...field.Expr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentEmergencySnapshotDo) Omit(cols ...field.Expr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentEmergencySnapshotDo) Join(table schema.Tabler, on ...field.Expr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentEmergencySnapshotDo) LeftJoin(table schema.Tabler, on ...field.Expr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentEmergencySnapshotDo) RightJoin(table schema.Tabler, on ...field.Expr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentEmergencySnapshotDo) Group(cols ...field.Expr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentEmergencySnapshotDo) Having(conds ...gen.Condition) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentEmergencySnapshotDo) Limit(limit int) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentEmergencySnapshotDo) Offset(offset int) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentEmergencySnapshotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentEmergencySnapshotDo) Unscoped() *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentEmergencySnapshotDo) Create(values ...*model.AgentEmergencySnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentEmergencySnapshotDo) CreateInBatches(values []*model.AgentEmergencySnapshot, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentEmergencySnapshotDo) Save(values ...*model.AgentEmergencySnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentEmergencySnapshotDo) First() (*model.AgentEmergencySnapshot, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentEmergencySnapshot), nil
	}
}

func (a agentEmergencySnapshotDo) Take() (*model.AgentEmergencySnapshot, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentEmergencySnapshot), nil
	}
}

func (a agentEmergencySnapshotDo) Last() (*model.AgentEmergencySnapshot, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentEmergencySnapshot), nil
	}
}

func (a agentEmergencySnapshotDo) Find() ([]*model.AgentEmergencySnapshot, error) {
	result, err := a.DO.Find()
	return result.([]*model.AgentEmergencySnapshot), err
}

func (a agentEmergencySnapshotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AgentEmergencySnapshot, err error) {
	buf := make([]*model.AgentEmergencySnapshot, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentEmergencySnapshotDo) FindInBatches(result *[]*model.AgentEmergencySnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentEmergencySnapshotDo) Attrs(attrs ...field.AssignExpr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentEmergencySnapshotDo) Assign(attrs ...field.AssignExpr) *agentEmergencySnapshotDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentEmergencySnapshotDo) Joins(fields ...field.RelationField) *agentEmergencySnapshotDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentEmergencySnapshotDo) Preload(fields ...field.RelationField) *agentEmergencySnapshotDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentEmergencySnapshotDo) FirstOrInit() (*model.AgentEmergencySnapshot, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentEmergencySnapshot), nil
	}
}

func (a agentEmergencySnapshotDo) FirstOrCreate() (*model.AgentEmergencySnapshot, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentEmergencySnapshot), nil
	}
}

func (a agentEmergencySnapshotDo) FindByPage(offset int, limit int) (result []*model.AgentEmergencySnapshot, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentEmergencySnapshotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentEmergencySnapshotDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentEmergencySnapshotDo) Delete(models ...*model.AgentEmergencySnapshot) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentEmergencySnapshotDo) withDO(do gen.Dao) *agentEmergencySnapshotDo {
	a.DO = *do.(*gen.DO)
	return a
}
