// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common-mb/dal/model"
)

func newCertificate2(db *gorm.DB, opts ...gen.DOOption) certificate2 {
	_certificate2 := certificate2{}

	_certificate2.certificate2Do.UseDB(db, opts...)
	_certificate2.certificate2Do.UseModel(&model.Certificate2{})

	tableName := _certificate2.certificate2Do.TableName()
	_certificate2.ALL = field.NewAsterisk(tableName)
	_certificate2.ID = field.NewInt64(tableName, "id")
	_certificate2.Enabled = field.NewBool(tableName, "enabled")
	_certificate2.CommonName = field.NewString(tableName, "common_name")
	_certificate2.PublicKey = field.NewBytes(tableName, "public_key")
	_certificate2.PrivateKey = field.NewBytes(tableName, "private_key")
	_certificate2.CertificateSHA256 = field.NewString(tableName, "certificate_sha256")
	_certificate2.PublicKeySHA256 = field.NewString(tableName, "public_key_sha256")
	_certificate2.PrivateKeySHA256 = field.NewString(tableName, "private_key_sha256")
	_certificate2.DNSNames = field.NewField(tableName, "dns_names")
	_certificate2.IPAddresses = field.NewField(tableName, "ip_addresses")
	_certificate2.EmailAddresses = field.NewField(tableName, "email_addresses")
	_certificate2.URIs = field.NewField(tableName, "uris")
	_certificate2.Version = field.NewInt(tableName, "version")
	_certificate2.NotBefore = field.NewTime(tableName, "not_before")
	_certificate2.NotAfter = field.NewTime(tableName, "not_after")
	_certificate2.Issuer = field.NewField(tableName, "issuer")
	_certificate2.Subject = field.NewField(tableName, "subject")
	_certificate2.UpdatedAt = field.NewTime(tableName, "created_at")
	_certificate2.CreatedAt = field.NewTime(tableName, "updated_at")

	_certificate2.fillFieldMap()

	return _certificate2
}

type certificate2 struct {
	certificate2Do certificate2Do

	ALL               field.Asterisk
	ID                field.Int64  // ID
	Enabled           field.Bool   // 是否启用
	CommonName        field.String // 共用名
	PublicKey         field.Bytes  // 证书
	PrivateKey        field.Bytes  // 私钥
	CertificateSHA256 field.String // 证书指纹
	PublicKeySHA256   field.String // 公钥指纹
	PrivateKeySHA256  field.String // 私钥指纹
	DNSNames          field.Field  // 域名
	IPAddresses       field.Field  // IP
	EmailAddresses    field.Field  // 邮箱
	URIs              field.Field  // URI
	Version           field.Int    // 版本
	NotBefore         field.Time   // 生效时间
	NotAfter          field.Time   // 过期时间
	Issuer            field.Field  // 颁发者
	Subject           field.Field  // 主题
	UpdatedAt         field.Time   // 创建时间
	CreatedAt         field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c certificate2) Table(newTableName string) *certificate2 {
	c.certificate2Do.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c certificate2) As(alias string) *certificate2 {
	c.certificate2Do.DO = *(c.certificate2Do.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *certificate2) updateTableName(table string) *certificate2 {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Enabled = field.NewBool(table, "enabled")
	c.CommonName = field.NewString(table, "common_name")
	c.PublicKey = field.NewBytes(table, "public_key")
	c.PrivateKey = field.NewBytes(table, "private_key")
	c.CertificateSHA256 = field.NewString(table, "certificate_sha256")
	c.PublicKeySHA256 = field.NewString(table, "public_key_sha256")
	c.PrivateKeySHA256 = field.NewString(table, "private_key_sha256")
	c.DNSNames = field.NewField(table, "dns_names")
	c.IPAddresses = field.NewField(table, "ip_addresses")
	c.EmailAddresses = field.NewField(table, "email_addresses")
	c.URIs = field.NewField(table, "uris")
	c.Version = field.NewInt(table, "version")
	c.NotBefore = field.NewTime(table, "not_before")
	c.NotAfter = field.NewTime(table, "not_after")
	c.Issuer = field.NewField(table, "issuer")
	c.Subject = field.NewField(table, "subject")
	c.UpdatedAt = field.NewTime(table, "created_at")
	c.CreatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *certificate2) WithContext(ctx context.Context) *certificate2Do {
	return c.certificate2Do.WithContext(ctx)
}

func (c certificate2) TableName() string { return c.certificate2Do.TableName() }

func (c certificate2) Alias() string { return c.certificate2Do.Alias() }

func (c certificate2) Columns(cols ...field.Expr) gen.Columns {
	return c.certificate2Do.Columns(cols...)
}

func (c *certificate2) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *certificate2) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 19)
	c.fieldMap["id"] = c.ID
	c.fieldMap["enabled"] = c.Enabled
	c.fieldMap["common_name"] = c.CommonName
	c.fieldMap["public_key"] = c.PublicKey
	c.fieldMap["private_key"] = c.PrivateKey
	c.fieldMap["certificate_sha256"] = c.CertificateSHA256
	c.fieldMap["public_key_sha256"] = c.PublicKeySHA256
	c.fieldMap["private_key_sha256"] = c.PrivateKeySHA256
	c.fieldMap["dns_names"] = c.DNSNames
	c.fieldMap["ip_addresses"] = c.IPAddresses
	c.fieldMap["email_addresses"] = c.EmailAddresses
	c.fieldMap["uris"] = c.URIs
	c.fieldMap["version"] = c.Version
	c.fieldMap["not_before"] = c.NotBefore
	c.fieldMap["not_after"] = c.NotAfter
	c.fieldMap["issuer"] = c.Issuer
	c.fieldMap["subject"] = c.Subject
	c.fieldMap["created_at"] = c.UpdatedAt
	c.fieldMap["updated_at"] = c.CreatedAt
}

func (c certificate2) clone(db *gorm.DB) certificate2 {
	c.certificate2Do.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c certificate2) replaceDB(db *gorm.DB) certificate2 {
	c.certificate2Do.ReplaceDB(db)
	return c
}

type certificate2Do struct{ gen.DO }

func (c certificate2Do) Debug() *certificate2Do {
	return c.withDO(c.DO.Debug())
}

func (c certificate2Do) WithContext(ctx context.Context) *certificate2Do {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c certificate2Do) ReadDB() *certificate2Do {
	return c.Clauses(dbresolver.Read)
}

func (c certificate2Do) WriteDB() *certificate2Do {
	return c.Clauses(dbresolver.Write)
}

func (c certificate2Do) Session(config *gorm.Session) *certificate2Do {
	return c.withDO(c.DO.Session(config))
}

func (c certificate2Do) Clauses(conds ...clause.Expression) *certificate2Do {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c certificate2Do) Returning(value interface{}, columns ...string) *certificate2Do {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c certificate2Do) Not(conds ...gen.Condition) *certificate2Do {
	return c.withDO(c.DO.Not(conds...))
}

func (c certificate2Do) Or(conds ...gen.Condition) *certificate2Do {
	return c.withDO(c.DO.Or(conds...))
}

func (c certificate2Do) Select(conds ...field.Expr) *certificate2Do {
	return c.withDO(c.DO.Select(conds...))
}

func (c certificate2Do) Where(conds ...gen.Condition) *certificate2Do {
	return c.withDO(c.DO.Where(conds...))
}

func (c certificate2Do) Order(conds ...field.Expr) *certificate2Do {
	return c.withDO(c.DO.Order(conds...))
}

func (c certificate2Do) Distinct(cols ...field.Expr) *certificate2Do {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c certificate2Do) Omit(cols ...field.Expr) *certificate2Do {
	return c.withDO(c.DO.Omit(cols...))
}

func (c certificate2Do) Join(table schema.Tabler, on ...field.Expr) *certificate2Do {
	return c.withDO(c.DO.Join(table, on...))
}

func (c certificate2Do) LeftJoin(table schema.Tabler, on ...field.Expr) *certificate2Do {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c certificate2Do) RightJoin(table schema.Tabler, on ...field.Expr) *certificate2Do {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c certificate2Do) Group(cols ...field.Expr) *certificate2Do {
	return c.withDO(c.DO.Group(cols...))
}

func (c certificate2Do) Having(conds ...gen.Condition) *certificate2Do {
	return c.withDO(c.DO.Having(conds...))
}

func (c certificate2Do) Limit(limit int) *certificate2Do {
	return c.withDO(c.DO.Limit(limit))
}

func (c certificate2Do) Offset(offset int) *certificate2Do {
	return c.withDO(c.DO.Offset(offset))
}

func (c certificate2Do) Scopes(funcs ...func(gen.Dao) gen.Dao) *certificate2Do {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c certificate2Do) Unscoped() *certificate2Do {
	return c.withDO(c.DO.Unscoped())
}

func (c certificate2Do) Create(values ...*model.Certificate2) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c certificate2Do) CreateInBatches(values []*model.Certificate2, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c certificate2Do) Save(values ...*model.Certificate2) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c certificate2Do) First() (*model.Certificate2, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate2), nil
	}
}

func (c certificate2Do) Take() (*model.Certificate2, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate2), nil
	}
}

func (c certificate2Do) Last() (*model.Certificate2, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate2), nil
	}
}

func (c certificate2Do) Find() ([]*model.Certificate2, error) {
	result, err := c.DO.Find()
	return result.([]*model.Certificate2), err
}

func (c certificate2Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Certificate2, err error) {
	buf := make([]*model.Certificate2, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c certificate2Do) FindInBatches(result *[]*model.Certificate2, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c certificate2Do) Attrs(attrs ...field.AssignExpr) *certificate2Do {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c certificate2Do) Assign(attrs ...field.AssignExpr) *certificate2Do {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c certificate2Do) Joins(fields ...field.RelationField) *certificate2Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c certificate2Do) Preload(fields ...field.RelationField) *certificate2Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c certificate2Do) FirstOrInit() (*model.Certificate2, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate2), nil
	}
}

func (c certificate2Do) FirstOrCreate() (*model.Certificate2, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate2), nil
	}
}

func (c certificate2Do) FindByPage(offset int, limit int) (result []*model.Certificate2, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c certificate2Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c certificate2Do) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c certificate2Do) Delete(models ...*model.Certificate2) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *certificate2Do) withDO(do gen.Dao) *certificate2Do {
	c.DO = *do.(*gen.DO)
	return c
}
