// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/vela-common-mb/dal/model"
)

func newRotate(db *gorm.DB, opts ...gen.DOOption) rotate {
	_rotate := rotate{}

	_rotate.rotateDo.UseDB(db, opts...)
	_rotate.rotateDo.UseModel(&model.Rotate{})

	tableName := _rotate.rotateDo.TableName()
	_rotate.ALL = field.NewAsterisk(tableName)
	_rotate.ID = field.NewString(tableName, "id")
	_rotate.DayNum = field.NewInt(tableName, "day_num")
	_rotate.RowNum = field.NewInt(tableName, "row_num")
	_rotate.CreatedAt = field.NewTime(tableName, "created_at")
	_rotate.UpdatedAt = field.NewTime(tableName, "updated_at")

	_rotate.fillFieldMap()

	return _rotate
}

type rotate struct {
	rotateDo rotateDo

	ALL       field.Asterisk
	ID        field.String
	DayNum    field.Int
	RowNum    field.Int
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r rotate) Table(newTableName string) *rotate {
	r.rotateDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rotate) As(alias string) *rotate {
	r.rotateDo.DO = *(r.rotateDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rotate) updateTableName(table string) *rotate {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.DayNum = field.NewInt(table, "day_num")
	r.RowNum = field.NewInt(table, "row_num")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *rotate) WithContext(ctx context.Context) *rotateDo { return r.rotateDo.WithContext(ctx) }

func (r rotate) TableName() string { return r.rotateDo.TableName() }

func (r rotate) Alias() string { return r.rotateDo.Alias() }

func (r *rotate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rotate) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["id"] = r.ID
	r.fieldMap["day_num"] = r.DayNum
	r.fieldMap["row_num"] = r.RowNum
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r rotate) clone(db *gorm.DB) rotate {
	r.rotateDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rotate) replaceDB(db *gorm.DB) rotate {
	r.rotateDo.ReplaceDB(db)
	return r
}

type rotateDo struct{ gen.DO }

func (r rotateDo) Debug() *rotateDo {
	return r.withDO(r.DO.Debug())
}

func (r rotateDo) WithContext(ctx context.Context) *rotateDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rotateDo) ReadDB() *rotateDo {
	return r.Clauses(dbresolver.Read)
}

func (r rotateDo) WriteDB() *rotateDo {
	return r.Clauses(dbresolver.Write)
}

func (r rotateDo) Session(config *gorm.Session) *rotateDo {
	return r.withDO(r.DO.Session(config))
}

func (r rotateDo) Clauses(conds ...clause.Expression) *rotateDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rotateDo) Returning(value interface{}, columns ...string) *rotateDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rotateDo) Not(conds ...gen.Condition) *rotateDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rotateDo) Or(conds ...gen.Condition) *rotateDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rotateDo) Select(conds ...field.Expr) *rotateDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rotateDo) Where(conds ...gen.Condition) *rotateDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rotateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *rotateDo {
	return r.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (r rotateDo) Order(conds ...field.Expr) *rotateDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rotateDo) Distinct(cols ...field.Expr) *rotateDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rotateDo) Omit(cols ...field.Expr) *rotateDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rotateDo) Join(table schema.Tabler, on ...field.Expr) *rotateDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rotateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *rotateDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rotateDo) RightJoin(table schema.Tabler, on ...field.Expr) *rotateDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rotateDo) Group(cols ...field.Expr) *rotateDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rotateDo) Having(conds ...gen.Condition) *rotateDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rotateDo) Limit(limit int) *rotateDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rotateDo) Offset(offset int) *rotateDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rotateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *rotateDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rotateDo) Unscoped() *rotateDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rotateDo) Create(values ...*model.Rotate) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rotateDo) CreateInBatches(values []*model.Rotate, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rotateDo) Save(values ...*model.Rotate) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rotateDo) First() (*model.Rotate, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rotate), nil
	}
}

func (r rotateDo) Take() (*model.Rotate, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rotate), nil
	}
}

func (r rotateDo) Last() (*model.Rotate, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rotate), nil
	}
}

func (r rotateDo) Find() ([]*model.Rotate, error) {
	result, err := r.DO.Find()
	return result.([]*model.Rotate), err
}

func (r rotateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Rotate, err error) {
	buf := make([]*model.Rotate, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rotateDo) FindInBatches(result *[]*model.Rotate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rotateDo) Attrs(attrs ...field.AssignExpr) *rotateDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rotateDo) Assign(attrs ...field.AssignExpr) *rotateDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rotateDo) Joins(fields ...field.RelationField) *rotateDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rotateDo) Preload(fields ...field.RelationField) *rotateDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rotateDo) FirstOrInit() (*model.Rotate, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rotate), nil
	}
}

func (r rotateDo) FirstOrCreate() (*model.Rotate, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Rotate), nil
	}
}

func (r rotateDo) FindByPage(offset int, limit int) (result []*model.Rotate, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rotateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rotateDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rotateDo) Delete(models ...*model.Rotate) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rotateDo) withDO(do gen.Dao) *rotateDo {
	r.DO = *do.(*gen.DO)
	return r
}
