// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/ssoc-common-mb/dal/model"
)

func newVictoriaMetricsConfig(db *gorm.DB, opts ...gen.DOOption) victoriaMetricsConfig {
	_victoriaMetricsConfig := victoriaMetricsConfig{}

	_victoriaMetricsConfig.victoriaMetricsConfigDo.UseDB(db, opts...)
	_victoriaMetricsConfig.victoriaMetricsConfigDo.UseModel(&model.VictoriaMetricsConfig{})

	tableName := _victoriaMetricsConfig.victoriaMetricsConfigDo.TableName()
	_victoriaMetricsConfig.ALL = field.NewAsterisk(tableName)
	_victoriaMetricsConfig.ID = field.NewInt64(tableName, "id")
	_victoriaMetricsConfig.Name = field.NewString(tableName, "name")
	_victoriaMetricsConfig.Enabled = field.NewBool(tableName, "enabled")
	_victoriaMetricsConfig.Method = field.NewString(tableName, "method")
	_victoriaMetricsConfig.URL = field.NewString(tableName, "url")
	_victoriaMetricsConfig.Username = field.NewString(tableName, "username")
	_victoriaMetricsConfig.Password = field.NewString(tableName, "password")
	_victoriaMetricsConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_victoriaMetricsConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_victoriaMetricsConfig.fillFieldMap()

	return _victoriaMetricsConfig
}

type victoriaMetricsConfig struct {
	victoriaMetricsConfigDo victoriaMetricsConfigDo

	ALL       field.Asterisk
	ID        field.Int64  // ID
	Name      field.String // 名字
	Enabled   field.Bool   // 是否启用
	Method    field.String // 请求方法
	URL       field.String
	Username  field.String // 认证用户名
	Password  field.String // 认证密码
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (v victoriaMetricsConfig) Table(newTableName string) *victoriaMetricsConfig {
	v.victoriaMetricsConfigDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v victoriaMetricsConfig) As(alias string) *victoriaMetricsConfig {
	v.victoriaMetricsConfigDo.DO = *(v.victoriaMetricsConfigDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *victoriaMetricsConfig) updateTableName(table string) *victoriaMetricsConfig {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.Name = field.NewString(table, "name")
	v.Enabled = field.NewBool(table, "enabled")
	v.Method = field.NewString(table, "method")
	v.URL = field.NewString(table, "url")
	v.Username = field.NewString(table, "username")
	v.Password = field.NewString(table, "password")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *victoriaMetricsConfig) WithContext(ctx context.Context) *victoriaMetricsConfigDo {
	return v.victoriaMetricsConfigDo.WithContext(ctx)
}

func (v victoriaMetricsConfig) TableName() string { return v.victoriaMetricsConfigDo.TableName() }

func (v victoriaMetricsConfig) Alias() string { return v.victoriaMetricsConfigDo.Alias() }

func (v victoriaMetricsConfig) Columns(cols ...field.Expr) gen.Columns {
	return v.victoriaMetricsConfigDo.Columns(cols...)
}

func (v *victoriaMetricsConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *victoriaMetricsConfig) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 9)
	v.fieldMap["id"] = v.ID
	v.fieldMap["name"] = v.Name
	v.fieldMap["enabled"] = v.Enabled
	v.fieldMap["method"] = v.Method
	v.fieldMap["url"] = v.URL
	v.fieldMap["username"] = v.Username
	v.fieldMap["password"] = v.Password
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v victoriaMetricsConfig) clone(db *gorm.DB) victoriaMetricsConfig {
	v.victoriaMetricsConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v victoriaMetricsConfig) replaceDB(db *gorm.DB) victoriaMetricsConfig {
	v.victoriaMetricsConfigDo.ReplaceDB(db)
	return v
}

type victoriaMetricsConfigDo struct{ gen.DO }

func (v victoriaMetricsConfigDo) Debug() *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Debug())
}

func (v victoriaMetricsConfigDo) WithContext(ctx context.Context) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v victoriaMetricsConfigDo) ReadDB() *victoriaMetricsConfigDo {
	return v.Clauses(dbresolver.Read)
}

func (v victoriaMetricsConfigDo) WriteDB() *victoriaMetricsConfigDo {
	return v.Clauses(dbresolver.Write)
}

func (v victoriaMetricsConfigDo) Session(config *gorm.Session) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Session(config))
}

func (v victoriaMetricsConfigDo) Clauses(conds ...clause.Expression) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v victoriaMetricsConfigDo) Returning(value interface{}, columns ...string) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v victoriaMetricsConfigDo) Not(conds ...gen.Condition) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v victoriaMetricsConfigDo) Or(conds ...gen.Condition) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v victoriaMetricsConfigDo) Select(conds ...field.Expr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v victoriaMetricsConfigDo) Where(conds ...gen.Condition) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v victoriaMetricsConfigDo) Order(conds ...field.Expr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v victoriaMetricsConfigDo) Distinct(cols ...field.Expr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v victoriaMetricsConfigDo) Omit(cols ...field.Expr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v victoriaMetricsConfigDo) Join(table schema.Tabler, on ...field.Expr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v victoriaMetricsConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v victoriaMetricsConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v victoriaMetricsConfigDo) Group(cols ...field.Expr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v victoriaMetricsConfigDo) Having(conds ...gen.Condition) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v victoriaMetricsConfigDo) Limit(limit int) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v victoriaMetricsConfigDo) Offset(offset int) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v victoriaMetricsConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v victoriaMetricsConfigDo) Unscoped() *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Unscoped())
}

func (v victoriaMetricsConfigDo) Create(values ...*model.VictoriaMetricsConfig) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v victoriaMetricsConfigDo) CreateInBatches(values []*model.VictoriaMetricsConfig, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v victoriaMetricsConfigDo) Save(values ...*model.VictoriaMetricsConfig) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v victoriaMetricsConfigDo) First() (*model.VictoriaMetricsConfig, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetricsConfig), nil
	}
}

func (v victoriaMetricsConfigDo) Take() (*model.VictoriaMetricsConfig, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetricsConfig), nil
	}
}

func (v victoriaMetricsConfigDo) Last() (*model.VictoriaMetricsConfig, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetricsConfig), nil
	}
}

func (v victoriaMetricsConfigDo) Find() ([]*model.VictoriaMetricsConfig, error) {
	result, err := v.DO.Find()
	return result.([]*model.VictoriaMetricsConfig), err
}

func (v victoriaMetricsConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VictoriaMetricsConfig, err error) {
	buf := make([]*model.VictoriaMetricsConfig, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v victoriaMetricsConfigDo) FindInBatches(result *[]*model.VictoriaMetricsConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v victoriaMetricsConfigDo) Attrs(attrs ...field.AssignExpr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v victoriaMetricsConfigDo) Assign(attrs ...field.AssignExpr) *victoriaMetricsConfigDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v victoriaMetricsConfigDo) Joins(fields ...field.RelationField) *victoriaMetricsConfigDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v victoriaMetricsConfigDo) Preload(fields ...field.RelationField) *victoriaMetricsConfigDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v victoriaMetricsConfigDo) FirstOrInit() (*model.VictoriaMetricsConfig, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetricsConfig), nil
	}
}

func (v victoriaMetricsConfigDo) FirstOrCreate() (*model.VictoriaMetricsConfig, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VictoriaMetricsConfig), nil
	}
}

func (v victoriaMetricsConfigDo) FindByPage(offset int, limit int) (result []*model.VictoriaMetricsConfig, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v victoriaMetricsConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v victoriaMetricsConfigDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v victoriaMetricsConfigDo) Delete(models ...*model.VictoriaMetricsConfig) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *victoriaMetricsConfigDo) withDO(do gen.Dao) *victoriaMetricsConfigDo {
	v.DO = *do.(*gen.DO)
	return v
}
